# Project details
site_name: Chandler Cowell's Portfolio
site_url: https://cowellbunga.github.io/
site_author: Chandler Cowell
site_description: >-
  I am Chandler Cowell, an economist and spatial analytics master's student. 
  Welcome to my personal and professional page powered by Git/Github, Markdown, and Python.

# Github Repo
repo_name: cowellbunga/cowellbunga.github.io
repo_url: https://github.com/cowellbunga/cowellbunga.github.io

# Theme
theme:
  name: terminal
  features:
    - navigation.side.indexes
    - revision.date
    - revision.history

# Extensions
markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: 
        - docs

# Navigation Tree
nav:
  - Home: index.md
  - Skills: skills.md
  - Projects:
    - Index: projects/index.md
    - Active Projects:
      - Index: projects/active/index.md
      - Project 1: projects/active/project1.md
      - Project 2: projects/active/project2.md
    - Completed Projects:
      - Index: projects/completed/index.md
      - Project 1: projects/completed/project1.md
      - Project 2: projects/completed/project2.md

# Plugins
plugins:
  - search
  - git-revision-date
  - macros:
      modules: 
          - mkdocs-terminal:terminal.pluglets.tile_grid.main